### ISSUE TITLE
Looking for ways to custom your plugin

### ISSUE THREAD

**Issue by Think-It** [FaiblUG/jQuery-Lcn-Circle-Range-Select#1]
Hi !
First thank for your work. I was looking for a plugin like this since few months.

I'm interested for 2 features : 
1. Set in plugin's option min/max value (to make a clock for example :smile:)
2. Choose the size of the circle.

Currently in the CSS file I'd switched from : 

```
  width: 100px;
  border: 5px solid #ccc;
```

To :

```
  width: 200px;
  border: 15px solid #ccc;
```

But the .selected-range item don't follow the way ^^

Thank you !

**Comment by jfmaeck** [comment]
Hi,

thank your for your suggestions. I just pushed some changes that might solve your issues.

You can now add the following attributes to your input element:
data-min="0"
data-max="12"
data-unit="h"

Redefining the widget size using CSS should also work better now.

**Comment by Think-It** [comment]
Hi !

Great job.
Yesterday I was working on the same issues. Maybe I'll propose you a pull request with more options in few days :smiley:
