### ISSUE TITLE
set starting value from a middle value (not 0) and select value range from more than 360

### ISSUE THREAD

**Issue by dil25** [FaiblUG/jQuery-Lcn-Circle-Range-Select#2]
i need to customize this plugin to select year range. So i need to start year from 1960 and end should be 2015. So i need to select year range between these two years (1960 - 2015).. I tried to do it but no luck. I attached a screenshot that how it should want to be.

![image](https://cloud.githubusercontent.com/assets/4024987/7214511/021dea2a-e5cd-11e4-88c2-f00bec5f7a75.png)

**Comment by Think-It** [comment]
Hi,

You do do that with data-min and data-max : 

```
<input type="text" id="test-2" name="test-2" class="circle-range-select" value="0;6" data-min="1960" data-max="2015" data-unit="">
```

**Comment by dil25** [comment]
no luck..Still its starting from '0'.. I need to start it from 1960 and end should be 2015.

**Comment by jfmaeck** [comment]
Sorry, there was a bug with min values greater than zero. It should now be fixed.

This is the html that might work for you:

`<input type="text" id="test-2" name="test-2" class="circle-range-select" value="1960;2015" data-min="1960" data-max="2015" data-unit="">`

Hope that helps!

**Comment by dil25** [comment]
But when i slide again it showing the difference between values of 1960 - 2015 (55) and after that it will start from 0 and end from 55

**Comment by jfmaeck** [comment]
Hi, that is strange. In my test it is showing the year numbers when
sliding, not the difference between the year numbers. Are you really using
the latest version (1.0.9)?

Viele Grüße

Jonas Fischer-Maeck

## 

_Mobil_  0173 7000653
E-Mail info@jonasfischer.net
Web www.jonasfischer.net

**Comment by dil25** [comment]
Thanks god!! its working!!
