### ISSUE TITLE
Changing values programatically after page render

### ISSUE THREAD

**Issue by cillianomongain** [FaiblUG/jQuery-Lcn-Circle-Range-Select#4]
Hi 

Well done, love this selector. 

I was wondering if there was a way to manipulate the values with code after the page has rendered. For example:

``` javascript
$("#my-circle").val("45;90");
```

Or if there was a way to force it to redraw itself after I've manipulated the value on the html input element? I can get this to work to a degree using the code below but the problem is that it renders a new circle on top of the existing one.

``` javascript
$("#my-circle").lcnCircleRangeSelect();
```

Thanks

**Comment by jfmaeck** [comment]
HI @sillian,

thank you for opening this issue.
I'll try to make the widget re-render itself whenever the input's value changes.

However, it might take me a couple of days to find the time to do that. I'll update this issue when it's done.

Best Regards,

Jonas

**Comment by jfmaeck** [comment]
Hi @sillian,

if you update to version 2.1.0 it should work with this code:

```
$("#my-circle").val("45;90").trigger('change');
```

**Comment by cillianomongain** [comment]
Hi @jfmaeck 

Fantastic, that's great thanks. I had found a hack to work around it, removing the element, inserting new html code and re-rendering:

``` javascript
$('.circle-range-select-wrapper').hide();
$('td#circle1').html('<input type="text" class="circle-range-select" id="my-circle" data-auto-init value=newMinValue+";"+newMaxValue>');
$('#my-circle').lcnCircleRangeSelect();
```

But your solution is far more elegant. Cheers
