### ISSUE TITLE
How to get changed value in out side circle ?

### ISSUE THREAD

**Issue by baladkb** [FaiblUG/jQuery-Lcn-Circle-Range-Select#6]
Hi, @jfmaeck,
how we can use value in outside the circle, for example below I have added the screenshot please check.
![10-30-2017 1-54-11 pm](https://user-images.githubusercontent.com/4152211/32161278-ee8ebef2-bd7a-11e7-967f-c54b696dc646.png)
please guide us.

**Comment by jfmaeck** [comment]
Hi @baladkb,

the value of the input gets updated auomatically. I guess you want to liisten to the input's `change` or `update` events to get notified whenever the selected range is updated.

Hope this helps?

**Comment by baladkb** [comment]
@jfmaeck, Ok thanks 👍 I try this.
