### ISSUE TITLE
Can we reduce the moment(range rotation) speed ? 

### ISSUE THREAD

**Issue by baladkb** [FaiblUG/jQuery-Lcn-Circle-Range-Select#8]
Hi @jfmaeck,
sorry we have disturb You again, 
we can able to reduce the moment(range rotation) speed ?

Thanks :octocat:

**Comment by jfmaeck** [comment]
Sorry, I don't think this is possible at the moment.

**Comment by baladkb** [comment]
Ok @jfmaeck.
